/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Internal.AgregarProductos;
import Clases.*;
import Internal.*;
import java.util.TreeSet;

/**
 *
 * @author necoi
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    public Personalizados.Escritorio escritorio; //Se crea objeto tipo escritorio
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        escritorio = new Personalizados.Escritorio(); //Se inicializa escritorio
        this.setContentPane(escritorio); //Coloca el escritorio en el JFrame
        this.setTitle("De todo S.A."); //Coloca el titulo encabezado del JFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmbMenuOpciones = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        jmiAgregar = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiConsNombre = new javax.swing.JMenuItem();
        jmiConsPrecio = new javax.swing.JMenuItem();
        jmiConsRubro = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmAdministracion.setText("administracion");

        jmiAgregar.setText("Administracion");
        jmiAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiAgregar);

        jmbMenuOpciones.add(jmAdministracion);

        jmConsultas.setText("Consultas");

        jmiConsNombre.setText("Consulta por nombre");
        jmiConsNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsNombreActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsNombre);

        jmiConsPrecio.setText("Consulta por precio");
        jmiConsPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsPrecioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsPrecio);

        jmiConsRubro.setText("Consulta por rubro");
        jmiConsRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsRubroActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsRubro);

        jmbMenuOpciones.add(jmConsultas);

        jmSalir.setText("Salir");

        jmiSalir.setText("salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmSalir.add(jmiSalir);

        jmbMenuOpciones.add(jmSalir);

        setJMenuBar(jmbMenuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiConsNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsNombreActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BuscarPorNombre bpn = new BuscarPorNombre();
        bpn.setVisible(true);
        escritorio.add(bpn);
        escritorio.moveToFront(bpn);
    }//GEN-LAST:event_jmiConsNombreActionPerformed

    private void jmiConsPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiConsPrecioActionPerformed

    private void jmiConsRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsRubroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiConsRubroActionPerformed

    private void jmiAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AgregarProductos ap = new AgregarProductos();
        ap.setVisible(true);
        escritorio.add(ap);
        escritorio.moveToFront(ap);
    }//GEN-LAST:event_jmiAgregarActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
        System.out.println(evt.getActionCommand());
    }//GEN-LAST:event_jmiSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    public static Super superPC = new Super();
    public static TreeSet<Producto> productos = new TreeSet<>(Producto.compararPorCodigo);    
    public static CategoriasData categorias = new CategoriasData();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuBar jmbMenuOpciones;
    private javax.swing.JMenuItem jmiAgregar;
    private javax.swing.JMenuItem jmiConsNombre;
    private javax.swing.JMenuItem jmiConsPrecio;
    private javax.swing.JMenuItem jmiConsRubro;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
